# Autogenerated project build script
# Mon Apr  7 14:24:59 2014

gen_ipbus_addr_decode mp7_infra.xml
cp ipbus_decode_mp7_infra.vhd /home/scratch/vhdl/uGMT/dev/ipbus_lut_test/cactusupgrades/components/mp7_infra/firmware/hdl/ipbus_decode_mp7_infra.vhd
gen_ipbus_addr_decode mp7_ctrl.xml
cp ipbus_decode_mp7_ctrl.vhd /home/scratch/vhdl/uGMT/dev/ipbus_lut_test/cactusupgrades/components/mp7_ctrl/firmware/hdl/ipbus_decode_mp7_ctrl.vhd
gen_ipbus_addr_decode mp7_ttc.xml
cp ipbus_decode_mp7_ttc.vhd /home/scratch/vhdl/uGMT/dev/ipbus_lut_test/cactusupgrades/components/mp7_ttc/firmware/hdl/ipbus_decode_mp7_ttc.vhd
gen_ipbus_addr_decode mp7_datapath.xml
cp ipbus_decode_mp7_datapath.vhd /home/scratch/vhdl/uGMT/dev/ipbus_lut_test/cactusupgrades/components/mp7_datapath/firmware/hdl/ipbus_decode_mp7_datapath.vhd
gen_ipbus_addr_decode mp7_payload.xml
cp ipbus_decode_mp7_payload.vhd /home/scratch/vhdl/uGMT/dev/ipbus_lut_test/cactusupgrades/components/mp7_null_algo/firmware/hdl/ipbus_decode_mp7_payload.vhd
